.github/CODEOWNERS
We will add and clasify code owners depending on the file type (Language) later
=> initial code owner setup for all codes

src/Services/Identity/Identity.API/Identity.API.csproj, src/Services/Identity/Identity.API/Startup.cs
dotnet v3.0 preview4 make some changes that break our previous
code (v3.0-preview3)
closes #18
=> update for dotnet3preview4 breaking changes

src/Services/Identity/Identity.API/Controllers/HomeController.cs, src/Services/Identity/Identity.API/Identity.API.csproj, src/Services/Identity/Identity.API/Models/ErrorViewModel.cs, src/Services/Identity/Identity.API/Program.cs, src/Services/Identity/Identity.API/Startup.cs, src/Services/Identity/Identity.API/Views/_ViewImports.cshtml
Change namespace prefix to `OpenCodeFoundation.eSchool` 
closes #8
=> change default namespace

src/Services/Enrolling/Enrolling.API/Application/Validations/EnrollmentApplicationCommandValidator.cs, src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj, src/Services/Enrolling/Enrolling.API/Startup.cs
=> add fluent validation for anti-corruption layer

.github/workflows/enrolling.api.yml
=> Add GitHub CI pipeline for enrolling API

README.md
=> add system requirements and how to run instruction

.github/workflows/enrolling.api.yml, .gitignore, build/azure-devops/enrolling-api/azure-pipelines.yml, docker-compose-test.override.yml, docker-compose-test.yml, src/Services/Enrolling/Enrolling.API/Dockerfile, src/Services/Enrolling/Enrolling.UnitTests/Enrolling.UnitTests.csproj
Run unit tests in github action and Azure Pipeline 
Closes #40
=> Run enrolling unit tests in CI pipeline

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
=> add community health files

.github/workflows/joining.api.yml, build/azure-devops/joining-api/azure-pipelines.yml, docker-compose-test.override.yml, docker-compose-test.yml, docker-compose.override.yml, src/Services/Enrolling/Enrolling.API/Dockerfile, src/Services/Joining/Joining.API/Dockerfile, src/Web/WebStatus/Dockerfile
=> CI pipeline for Joining Service

src/Services/Enrolling/Enrolling.API/Program.cs, src/Services/Joining/Joining.API/Program.cs, src/Web/WebStatus/Program.cs
Check https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/ for more information
=> feat: enable w3c trace context support

src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj, src/Services/Enrolling/Enrolling.FunctionalTests/Enrolling.FunctionalTests.csproj, src/Services/Enrolling/Enrolling.Infrastructure/Enrolling.Infrastructure.csproj
This should fix enrolling service build
=> fix(enrolling): update NuGet packages

.github/workflows/enrolling.api.yml, docker-compose.yml
=> feat(enrolling): publish docker image to dockerhub

README.md
Thanks to everyone who have contributed to this repository (even you @dependabot-preview 😎)
=> chore(readme): add contributors image

.editorconfig, src/Services/Enrolling/Enrolling.API/Application/Commands/EnrollmentApplicationCommand.cs, src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj, src/Services/Enrolling/Enrolling.API/Program.cs, src/Services/Enrolling/Enrolling.API/Startup.cs, src/Services/Enrolling/Enrolling.API/graphql/GraphQlErrorFilter.cs, src/Services/Enrolling/Enrolling.API/graphql/Mutation.cs, src/Services/Enrolling/Enrolling.API/graphql/Query.cs, src/Services/Enrolling/Enrolling.Domain/Enrolling.Domain.csproj, src/Services/Enrolling/Enrolling.FunctionalTests/TestServerFixture.cs, src/Services/Enrolling/Enrolling.Infrastructure/Enrolling.Infrastructure.csproj, src/Services/Enrolling/Enrolling.Infrastructure/EnrollingContext.cs, src/Services/Enrolling/Enrolling.Infrastructure/Migrations/20200330154056_Initial.cs
- add Serilog request logging
- add span enricher for serilog
=> feat(enrolling): add GraphQL support

README.md, eSchool.sln, src/ApiGateways/eSchool.GraphQL/Dockerfile, src/Services/Enrolling/Enrolling.API/Dockerfile, src/Web/Frontend.Blazor/Frontend.Blazor.Client/Frontend.Blazor.Client.csproj, src/Web/Frontend.Blazor/Frontend.Blazor.Client/Program.cs, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Controllers/AppSettingsController.cs, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Dockerfile, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Frontend.Blazor.Server.csproj, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Program.cs, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Startup.cs, src/Web/Frontend.Blazor/Frontend.Blazor.Server/appsettings.json, src/Web/Frontend.Blazor/Frontend.Blazor.Shared/Frontend.Blazor.Shared.csproj, src/Web/Frontend.Blazor/Frontend.Blazor.Shared/FrontendSettings.cs, src/Web/WebStatus/Dockerfile
=> feat(frontend-blazor): read frontend configuration from host service

src/ApiGateways/eSchool.GraphQL/Dockerfile, src/Services/Enrolling/Enrolling.API/Dockerfile, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Dockerfile, src/Web/WebStatus/Dockerfile
Related issue https://github.com/NuGet/Home/issues/10491
=> fix: NuGet restore failing in docker build

src/ApiGateways/eSchool.GraphQL/Dockerfile, src/Services/Enrolling/Enrolling.API/Dockerfile, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Dockerfile, src/Web/WebStatus/Dockerfile
Using alpine throws exception -
```
Application startup exception: System.NotSupportedException: Globalization Invariant Mode is not supported.
at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
at Microsoft.Data.SqlClient.SqlConnection.Open()
...
```
So, using focal instead
related pr #292
=> fix: efcore sql connection error for alpine

src/ApiGateways/eSchool.GraphQL/eSchool.GraphQL.csproj, src/Libraries/OpenTelemetry/OpenTelemetry.csproj, src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj, src/Services/Enrolling/Enrolling.FunctionalTests/Enrolling.FunctionalTests.csproj, src/Services/Enrolling/Enrolling.Infrastructure/Enrolling.Infrastructure.csproj, src/Services/Enrolling/Enrolling.UnitTests/Enrolling.UnitTests.csproj, src/Web/Frontend.Blazor/Frontend.Blazor.Client/Frontend.Blazor.Client.csproj, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Frontend.Blazor.Server.csproj
Update most of the `NuGet` packages except the `Mudblazor` which is used in Blazor frontend. Need some changes on the code to update the `Mudblazor` package.
=> chore(deps): update nuget packages

CHANGELOG.md
* efcore sql globalization connection error ([#293](https://github.com/OpenCodeFoundation/eSchool/issues/293)) ([c4ace8a](https://github.com/OpenCodeFoundation/eSchool/commit/c4ace8a90377cc383e8308d07d7f94ff7ae0edd3))
* NuGet restore failing in docker build ([4a1fee9](https://github.com/OpenCodeFoundation/eSchool/commit/4a1fee98ac90bb382b522057bd08067b3b3a768e))
* **frontend-blazor:** update MudBlazor to  v5 ([#386](https://github.com/OpenCodeFoundation/eSchool/issues/386)) ([d5dc12d](https://github.com/OpenCodeFoundation/eSchool/commit/d5dc12d59b3870176061b6cba0dcf850bad3bb95))
* **pipeline:** better codeql pull request analysis ([#389](https://github.com/OpenCodeFoundation/eSchool/issues/389)) ([cf8f80a](https://github.com/OpenCodeFoundation/eSchool/commit/cf8f80af237b7867c8275864ebd0d66 …
=> release: cut the v0.7.0 release

.github/workflows/codeql-analysis.yml, src/ApiGateways/eSchool.GraphQL/Dockerfile, src/Services/CertificateProcessing/CertificateProcessing.API/Dockerfile, src/Services/Enrolling/Enrolling.API/Dockerfile, src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj, src/Services/Enrolling/Enrolling.Domain/Enrolling.Domain.csproj, src/Services/Enrolling/Enrolling.FunctionalTests/Enrolling.FunctionalTests.csproj, src/Services/Enrolling/Enrolling.Infrastructure/Enrolling.Infrastructure.csproj, src/Services/Enrolling/Enrolling.UnitTests/Enrolling.UnitTests.csproj, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Dockerfile, src/Web/WebStatus/Dockerfile
After the PR is merged, we will be able to update our services to dotnet v6
=> chore: update docker build and run environment to dotnet v6

src/ApiGateways/eSchool.GraphQL/Dockerfile, src/Services/CertificateProcessing/CertificateProcessing.API/Dockerfile, src/Services/Enrolling/Enrolling.API/Application/Commands/EnrollmentApplicationCommandHandler.cs, src/Services/Enrolling/Enrolling.API/Dockerfile, src/Services/Enrolling/Enrolling.API/Enrolling.API.csproj, src/Services/Enrolling/Enrolling.API/graphql/Mutation.cs, src/Services/Enrolling/Enrolling.Domain/AggregatesModel/EnrollmentAggregate/Enrollment.cs, src/Services/Enrolling/Enrolling.FunctionalTests/Enrolling.FunctionalTests.csproj, src/Services/Enrolling/Enrolling.Infrastructure/Enrolling.Infrastructure.csproj, src/Services/Enrolling/Enrolling.UnitTests/Domain/EnrollmentAggregateTests.cs, src/Web/Frontend.Blazor/Frontend.Blazor.Server/Dockerfile, src/Web/WebStatus/Dockerfile
- Separate docker files for each service
=> feat(enrolling): initial domain logic implementation 

src/Services/CertificateProcessing/CertificateProcessing.API/CertificateProcessing.API.csproj, src/Services/CertificateProcessing/CertificateProcessing.API/Program.cs, src/Services/CertificateProcessing/CertificateProcessing.API/Startup.cs
=> Integrate seq and serilog in certificate processing service

.github/workflows/certificate-processing.api.yml, .github/workflows/enrolling.api.yml, .github/workflows/eschool.graphql.yml, .github/workflows/frontend.blazor.yml, .github/workflows/webstatus.yml, build/azure-devops/enrolling-api/azure-pipelines.yml, build/azure-devops/eschool-graphql/azure-pipelines.yml, build/azure-devops/webstatus/azure-pipelines.yml
Update GitHub actions virtual environment to ubuntu latest
=> fix: github action build fix

src/Services/ExamManagement/ExamManagement.API/ExamManagement.API.csproj, src/Services/ExamManagement/ExamManagement.API/Program.cs, src/Services/ExamManagement/ExamManagement.API/Startup.cs
After merging PR #491, the service was not building. 
LEASON: Always build the solution manually before accepting the PR. The author may not build the project and submit `PR`
=> fix(exam-management): fix build
